version: "3"

services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - "${DOCKER_PATH}/plex/config:/config"
      - "${MEDIA_DIR}:/media"
    network_mode: "host"
    restart: unless_stopped

  sonarr: 
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - "${DOCKER_PATH}/sonarr/config:/config"
      - "${MEDIA_DIR}/tv:/tv"
      - "${DOWNLOAD_DIR}/torrents:/downloads"
    ports:
      - "8989:8989"
    network_mode: "bridge"
    restart: unless_stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - "${DOCKER_PATH}/radarr/config:/config"
      - "${MEDIA_DIR}/movies:/movies"
      - "${DOWNLOAD_DIR}/torrents:/downloads"
    ports: 
      - "7878:7878"
    network_mode: "bridge"
    restart: unless_stopped
  
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    volumes:
      - "${DOCKER_PATH}/vpn-client:/vpn"
    ports:
      - "9091:9091"
      - "9696:9696"
    network_mode: "bridge"
    environment:
      - VPN=${VPN}
      - ROUTE=${HOST_IP}
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    volumes:
      - "${DOCKER_PATH}/prowlarr/config:/config"
    network_mode: "container:[vpn]"
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    volumes:
      - "${DOCKER_PATH}/transmission/config:/config"
      - "${DOWNLOAD_DIR}/torrents:/downloads"
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
    network_mode: "container:[vpn]"
    restart: unless-stopped

  openbooks:
    container_name: openbooks
    image: evan-buss/openbooks:latest
    volumes:
      - "${DOWNLOAD_DIR}:/books"
    ports:
      - "4567:4567"
    command: --name iker_neptunus --persist -s irc.irchighway.net:9999
    network_mode: "bridge"
    restart: unless-stopped

  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    volumes:
      - "${DOCKER_PATH}/audiobookshelf/metdata:/metadata"
      - "${DOCKER_PATH}/audiobookshelf/config:/config"
      - "${MEDIA_DIR}/Audiobooks:/audiobooks"
    ports:
      - "13378:80"
    network_mode: "bridge"
    restart: unless-stopped

